CREATE TABLE projects(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL CHECK (name <> ''),
    priority integer NOT NULL, 
    description text,
    deliverydate date NOT NULL
);

CREATE TABLE tasks(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL CHECK (name <> ''),
    done BOOLEAN,
    projectId integer REFERENCES projects(id)
);

INSERT INTO projects(name,priority,description,deliverydate) values ('Make a qweb app',1,'Using Javascript','2020-01-01');

INSERT INTO projects(name,priority,description,deliverydate) values ('Make a app',1,'Dark','2020-02-02');

INSERT INTO projects (name,priority,description,deliverydate) values ('Make a movil',1,'Knex','2020-03-03');

/*INSERT TAKS DATA*/

INSERT INTO tasks(name,done,projectId) values ('donwload',false,1)

INSERT INTO tasks(name,done,projectId) values ('donwload UI WEB',false,1)

INSERT INTO tasks(name,done,projectId) values ('donwload Flutter',false,2)

INSERT INTO tasks(name,done,projectId) values ('Desing UI',false,2)